name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install poetry
        run: pipx install poetry
        shell: bash

      - uses: actions/setup-python@v6
        with:
          python-version: "3.9"
          architecture: "x64"
          cache: "poetry"

      - run: poetry install
        shell: bash

      - name: Publish package
        run: |
          poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
        shell: bash